In [2]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 1], [1, 1]])

In [3]:
a * b

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [7]:
a = np.array([[1, 2, 3, 4]])
b = np.array([[10, 20]]).T
a * b

array([[10, 20, 30, 40],
       [20, 40, 60, 80]])

In [8]:
b

array([[10],
       [20]])

In [9]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [11]:
a.T.ravel()

array([1, 4, 2, 5, 3, 6])

In [13]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a.reshape(3, 2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
a.reshape(6, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])