In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2, 3])

In [3]:
a + 1

array([1, 2, 3, 4])

In [4]:
a - 1

array([-1,  0,  1,  2])

In [5]:
a * 2

array([0, 2, 4, 6])

In [6]:
b = np.array([2, 4, 5, 3])

In [7]:
a * b

array([ 0,  4, 10,  9])

In [8]:
2 ** a

array([1, 2, 4, 8])

In [9]:
2 ** a -a

array([1, 1, 2, 5])

In [10]:
a = np.ones((2, 2))
a

array([[1., 1.],
       [1., 1.]])

In [11]:
a * a

array([[1., 1.],
       [1., 1.]])

In [12]:
a.dot(a)

array([[2., 2.],
       [2., 2.]])

In [13]:
a @ a

array([[2., 2.],
       [2., 2.]])

In [14]:
a = np.array([1, 2, 3])
b = np.array([2, 2, 2])
b > a

array([ True, False, False])

In [15]:
t = np.arange(4) * np.pi /4
t

array([0.        , 0.78539816, 1.57079633, 2.35619449])

In [16]:
np.sin(t)

array([0.        , 0.70710678, 1.        , 0.70710678])

In [17]:
np.cos(t)

array([ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17, -7.07106781e-01])

In [20]:
a = np.triu(np.ones((3, 3)),1)
a

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [21]:
a.T

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])

In [22]:
a

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [23]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
np.sum(a)

21

In [25]:
np.mean(a)

3.5

In [26]:
a.mean()

3.5

In [27]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [28]:
a.sum(axis = 0) # 行方向の和

array([5, 7, 9])

In [29]:
a.sum(axis = 1)　# 列方向の和

array([ 6, 15])

In [30]:
a[(0, 1)]

2

In [32]:
a = np.array([[4, 3, 5], [1, 2, 1]])
a.sort(axis = 1)
a

array([[3, 4, 5],
       [1, 1, 2]])

In [33]:
a = np.array([4, 3, 1, 2])

In [34]:
idx = a.argsort()

In [35]:
idx

array([2, 3, 1, 0])

In [36]:
a[idx]

array([1, 2, 3, 4])